import React from "react";
import { signOut } from "firebase/auth";
import { useNavigate } from "react-router-dom";
import DashboardNav from "../components/DashboardNav";
import TmdbCreditFooter from "../components/TmdbCreditFooter";
import { auth } from "../firebase";

const InfoPanel = ({ title, children, colors }) => (
  <section
    className="rounded-3xl p-5 md:p-6"
    style={{
      border: `1px solid ${colors.secondary}`,
      backgroundColor: `${colors.background}f2`,
    }}
  >
    <h3 className="text-xl font-bold md:text-2xl">{title}</h3>
    <div className="mt-3 text-sm leading-relaxed md:text-base" style={{ color: `${colors.text}c9` }}>
      {children}
    </div>
  </section>
);

const CreditsPage = ({ colors, themeMode, onToggleTheme, ThemeSwitch, user }) => {
  const navigate = useNavigate();

  const handleSignOut = async () => {
    await signOut(auth);
    navigate("/login");
  };

  return (
    <div
      className="min-h-screen"
      style={{
        backgroundColor: colors.background,
        color: colors.text,
        fontFamily: "Andika, sans-serif",
      }}
    >
      <DashboardNav
        colors={colors}
        themeMode={themeMode}
        onToggleTheme={onToggleTheme}
        ThemeSwitch={ThemeSwitch}
        user={user}
        onLogout={handleSignOut}
      />

      <main className="mx-auto grid w-full max-w-7xl gap-7 px-4 pb-10 pt-6 md:px-8">
        <section
          className="yoko-fade-up rounded-3xl p-5 md:p-7"
          style={{
            border: `1px solid ${colors.secondary}`,
            background: `linear-gradient(120deg, ${colors.secondary}88, ${colors.background})`,
          }}
        >
          <p className="text-sm font-semibold uppercase tracking-[0.18em]" style={{ color: colors.accent }}>
            About & Credits
          </p>
          <h2 className="mt-3 text-3xl font-bold md:text-5xl">Data Sources and Attribution</h2>
          <p className="mt-3 max-w-3xl text-sm leading-relaxed md:text-base" style={{ color: `${colors.text}c9` }}>
            YOKO uses external movie metadata and media responsibly by naming the source, linking back to it, and
            keeping its own recommendation logic separate from source ownership.
          </p>
        </section>

        <div className="grid gap-7 lg:grid-cols-2">
          <InfoPanel title="TMDB Movie Data" colors={colors}>
            <p>
              Movie titles, summaries, posters, backdrops, trailers, genres, ratings, release information, cast,
              crew, recommendations, and similar movie results are fetched from TMDB.
            </p>
            <p className="mt-3">
              This application uses TMDB and the TMDB APIs but is not endorsed, certified, or otherwise approved by
              TMDB.
            </p>
            <a
              href="https://www.themoviedb.org"
              target="_blank"
              rel="noreferrer"
              className="mt-4 inline-flex rounded-full px-5 py-3 text-sm font-semibold"
              style={{ backgroundColor: colors.primary, color: "#ffffff" }}
            >
              Visit TMDB
            </a>
          </InfoPanel>

          <InfoPanel title="AI Insights" colors={colors}>
            <p>
              Spoiler-free watch reasons and mood tags may be generated with Gemini AI when the backend is configured
              with a Gemini API key.
            </p>
            <p className="mt-3">
              AI insight text is generated by this app from available movie metadata; it is not a TMDB endorsement or
              official movie description.
            </p>
          </InfoPanel>
        </div>

        <InfoPanel title="Rights and Responsibilities" colors={colors}>
          <p>
            TMDB remains the source of TMDB API data and images. YOKO stores user-specific activity such as favourites,
            watch history, and recommendation signals to personalize the experience.
          </p>
          <p className="mt-3">
            The TMDB logo appears here and in the shared footer so users can clearly see where movie data and images
            come from.
          </p>
        </InfoPanel>
      </main>

      <TmdbCreditFooter colors={colors} />
    </div>
  );
};

export default CreditsPage;
